version: '3.7'

services:
   dev-python:
      container_name: rimutec-dev-python
      hostname: dev-python.local
      build:
         context: .
      working_dir: /src
      volumes:
         - ..:/src:cached
      command: >
         bash -c "sleep infinity"
      networks:
         rimutec:

networks:
   rimutec:
